### ISSUE TITLE
ngx-parallax@4 functionality

### ISSUE THREAD

**Issue by matbalazsi** [MattJeanes/ngx-parallax#8] opened 2018-06-09 16:54 UTC
After upgrading to version 4.0.0, the scrolling effect stopped working. My elements are now static

**Comment by AmyJeanes** [comment] 2018-06-17 17:43
Hi, sorry for delay only just round to looking at this. I've just tried it as per my example here: https://github.com/MattJeanes/ngx-parallax/issues/4#issuecomment-357820561

And it seems to be working ok.

https://i.imgur.com/JYiiEg7.gifv

Can you provide an example app to reproduce issue? Thanks

**Comment by matbalazsi** [comment] 2018-06-20 13:40
Hi, 
I have found my issue! The parallax only works when the image was set in css. Oddly, this behavior has changed since the previous release.

**Not working**

`<img class="jumbotron-image" parallax src="assets/images/photos/car-tunnel.jpg">`

**Working**

`<div class="jumbotron-image  car-tunnel" parallax  ></div>`

```
.car-tunnel
{
   background-image: url('assets/images/photos/car-tunnel.jpg');
}
```

```
.jumbotron-image {
    object-fit: cover;
    object-position: 0;
    width: 100%;
    height: 100vh;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    z-index: 0;
    filter: grayscale(1) brightness(1.2) contrast(0.8);
}
```

**Comment by AmyJeanes** [comment] 2018-06-20 15:10
Huh, I'd have thought it would have never have worked when using `<img src=''>`, it explicitly alters the background image position to achieve the parallax effect and would not work on a normal image.

Since the documentation (and code) shows that it's supposed to be used with `background-image` I will close this issue as it's working as intended, but I'm glad you've managed to work out what was wrong.

**Closed as completed by AmyJeanes** 2018-06-20 15:10 UTC
